### ISSUE TITLE
What is GeneratorName

### ISSUE THREAD

**Issue by Trumpetbob42** [shoghicp/SimpleWorlds#3]
I have been looking and can't seem to find it.  For the command:
/swg <seed> <generatorName> <worldName>

What is to be used for generator name?  What are the options?
Thanks.

**Comment by PEMapModder** [comment]
Search `implements LevelGenerator` in the PocketMine source.
In the current `master` branch of `PocketMine/PocketMine-MP`, there are `NormalGenerator` and `SuperflatGenerator`.
In (your directory)/plugins/SimpleWorlds/config.yml, the default "default generator" is `SuperflatGenerator`. If you supply a non-exist or wrong generator, it would use the "default generator", which means, it will generate a new world using the generator in the config.
