### ISSUE TITLE
Error World Name not found?

### ISSUE THREAD

**Issue by jesusflores** [shoghicp/SimpleWorlds#5]
im new to this, I currently generated a new world; went through the procedure using the level name I made, however when I tried loading the level, it wasn't even generated.

**Comment by shoghicp** [comment]
you have to generate it first, then load the level

**Comment by programmorem** [comment]
Im new at Git Hub and Pocket Mine!I don't what API is!(What is the API)
I have download the Plugin but the Server didnt know the commands!What I must do?
Please help me in time! 
And sorry for the badly Englisch! ( I'm speak German!)
